In [2]:
import numpy as numy

array = numy.array([[1,11,23,4] , [3,5,1,6]])
print(array [1, 1:4])


[5 1 6]


In [3]:
import numpy as numy

array = numy.array([[1,11,23,4] , [3,5,1,6]])
print(array [1, 3])

6


In [9]:
import numpy as numy

array = numy.array([[1,11,23,4] , [3,5,1,6],[0,9,5,2]])
print(array [0:2,:])

[[ 1 11 23  4]
 [ 3  5  1  6]]


In [10]:
import numpy as numy

array = numy.array([[1,11,23,4] , [3,5,1,6],[0,9,5,2]])
print(array [:,1:3])

[[11 23]
 [ 5  1]
 [ 9  5]]
